spring.application.name=HospitalManagementSystem

#db configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HospitalDB
spring.datasource.username=postgres
spring.datasource.password=root@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#to seed data while application starts
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
